# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 388097574d4692804baf8979009261e13a3e73e81fb2fe5ef307385487f6b344a2c188cc12648086445a915c4cb46f0e872c8a6280d8887b01111a1afa25aafc

test:
  secret_key_base: fd83fe2c911672141d9b1ba4e84bfb8ab9de5bd1143d2401bd995890cc6bd6bda110ab23ed4bae044ba267d0c58eda4c5965251f4ba8dc693f1439ab01cdf8ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
